### ISSUE TITLE
Too strict prettier

### ISSUE THREAD

**Issue by suomiy** [kubevirt/web-ui-components#19]
Prettier doesn't allow [option to retain multi-line props in JSX](https://github.com/prettier/prettier/issues/3101) which I think is very inhibiting. I propose removing prettier and find reasonable eslint rules instead.

Pros:
- better readability
- easier code review when changing props
- code consistency when reading multiply components bellow each other

Also I would like to propose:
- enforcing trailing commas (better diffs) 
- removing semicolons
  - less stuff to care about
  - semicolons can still be used in a very rare cases when they are needed ([semi](https://eslint.org/docs/rules/semi): `"never" disallows semicolons as the end of statements (except to disambiguate statements beginning with [, (, /, +, or -)`)

**Comment by mareklibra** [comment]
I'm not big fan of prettier. I believe we can get same service with properly set eslint rules. From my perspective, the reason to bare with it is to stay aligned with other projects, namely pf-react. And since this is higher priority, I can live with that ...

Regarding multi-line props - I have yet another preference :-) I like to keep props on a single line if not too long - let's say for up to 2 or 3 short props. This is easy to achieve with eslint, not sure about prettier.

| enforcing trailing commas (better diffs)

+1

| removing semicolons 

We are about jumping between OKD, web-ui, pf-react and maybe more. Removing semicolons just for this project will be confusing, since the rest of the projects use them.

**Comment by ohadlevy** [comment]
I'm generally in favor of prettier, the main motivation is anti bike shedding on how the code looks (which usually takes a long discussions for very little value imho).

I find the end result readable and useful, so +1 to keep it as is :)

**Comment by suomiy** [comment]
> I believe we can get same service with properly set eslint rules. 

+1
 I also think we could achieve more usable experience with same results as  prettier with eslint.

> Regarding multi-line props - I have yet another preference :-) I like to keep props on a single line if not too long - let's say for up to 2 or 3 short props. This is easy to achieve with eslint, not sure about prettier.

I like this preference as well, but it cannot be done with prettier.

The code is very difficult to read with too many props on a single line + also formatting is inconsistent.

> We are about jumping between OKD, web-ui, pf-react and maybe more. Removing semicolons just for this project will be confusing, since the rest of the projects use them.

Ok, I see.

> I'm generally in favor of prettier, the main motivation is anti bike shedding on how the code looks (which usually takes a long discussions for very little value imho).

I agree
