### ISSUE TITLE
Add popover to consumer item explaining the query and result presentation

### ISSUE THREAD

**Issue by rawagner** [kubevirt/web-ui-components#313]
I talked to @jelkosz and we concluded that it would be good to include some icon with a popover that would explain what is happening. E.g. `something something, The value xy is relative to the current higest value (100% bar)`. It could also include something about the query.

_Originally posted by @suomiy in https://github.com/kubevirt/web-ui-components/pull/289_

**Comment by rawagner** [comment]
@andybraren I have a few questions regarding Top Consumers card
1. Consumer bar is always 100% for the biggest consumer and other consumers are relative to it. IMO it does not make sense to show consumption bar against total resources because you would usually end up with a very small bar (ie cluster has 7TB memory and top consumers are using 5,4,3,2,1 GB ) Can we do something to make sure user is not confused here ?

2. Another question is about dropdowns - first one is Pods & VMs - what is the other value ? Nodes or Infrastructure ?

3. For Pods&VMs we are showing Workload as a 'title' above pod names. When user selects Nodes or Infrastructure what should be shown ? 

4. for CPU metrics we are showing CPU Time as a 'title' above actual values, is it ok to show Network consumption, Storage consumption and Memory consumption for other metrics ?

**Comment by andybraren** [comment]
For anyone following along, here's the current design:
![0g-consumption](https://user-images.githubusercontent.com/9122899/55653939-f60d1a00-57bd-11e9-9d25-be01042b1f7a.png)

And here's the implementation I see in Cosmos:
<img width="568" alt="2019-04-05 16 17 24" src="https://user-images.githubusercontent.com/9122899/55654059-500ddf80-57be-11e9-8f1d-cbcddd2bcdb5.png">

1. I think we're in agreement. The top blue bar is always 100% width and the ones below it are relative to it. It definitely doesn't make sense to size the bar against the total resource. The top consumer might be using just 1 GiB of the cluster's 7 TiB of storage, but the blue bar should still be 100% width. One difference in the design is that we show the actual number (and unit) to the right of the blue bar so that hovering isn't required.

2. The design document has the latest options (we're working on moving this to GitHub soon) but as of right now we're thinking:

- Projects
- Storage Classes
- Nodes
- Bare Metal Hosts (including masters)
- Pods & VMs (Pod/VM would be the title above the names, as shown above)
- Processes

We're still digging into each of these options though, so this isn't set in stone. Regarding "Infrastructure", we're still looking into the best way to allow the user to filter out all infra-related workloads (Pods/VMs/other). For now they're mixed in with everything else. Do you mean something else by "Infrastructure" we should also think about?

3. I would expect "Node" to be the title above each node name. "Infrastructure" isn't a planned option at the moment, but I'd like to learn more if you think it should be included as a dropdown option. (Side note: we ended up changing "Workloads" which was slightly unclear to "Pods & VMs" in the dropdown, which means the title above names is now "Pod/VM")

4. Those titles sound good to me. 🙂👍

**Comment by andybraren** [comment]
Oh, and regarding:

> it would be good to include some icon with a popover that would explain what is happening. E.g. something something, The value xy is relative to the current higest value (100% bar). It could also include something about the query.

I think the design of the blue bars (with the first being 100% width even if it's just 1 GiB, and all others sized relative to it) should be clear enough to users that info about its design shouldn't be needed. I know there was a discussion elsewhere about this though, so if you disagree or we're missing something let us know!

**Comment by suomiy** [comment]
> I think the design of the blue bars (with the first being 100% width even if it's just 1 GiB, and all others sized relative to it)  should be clear enough to users that info about its design shouldn't be needed

The storage is probably intuitive, but CPU consumption is not.

**Comment by andybraren** [comment]
@suomiy I'd like to learn more, could you elaborate? If the blue bars don't make sense when showing CPU time, we'd definitely like to improve the design.

**Comment by suomiy** [comment]
I guess it makes sense if you know that you have to look at the numbers. Because you cannot infer much useful information just from looking at the bars. That is why I would rather put the explanation there.
