### ISSUE TITLE
CreateVmWizard: disable cancel button on the last step

### ISSUE THREAD

**Issue by suomiy** [kubevirt/web-ui-components#61]
once https://github.com/patternfly/patternfly-react/pull/801 is merged

**Comment by rawagner** [comment]
I would be also cool to have ability to not show the button at all. WDYT ? We could show just Close and remove Back And Cancel in Results Tab

**Comment by lizsurette** [comment]
> I would be also cool to have ability to not show the button at all. WDYT ? We could show just Close and remove Back And Cancel in Results Tab

I mentioned exactly the same thing and @suomiy created a [PR](https://github.com/patternfly/patternfly-react/pull/743) to address this and then we were reminded that the PatternFly guidelines say that they should just be disabled. Also, Serena confirmed that this is the way the console is doing it, so we figure it's good to stay inline with that for now. I think I might push this in the PatternFly community, though because it makes total sense to me to work this way :)
